apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 1 pods matching the template
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        diamanti.com/endpoint0: '{"endpointId":"nginx","perfTier":"high"}'
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: core.harbor.domain/library/mynginx:1.2
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: appserv87
