apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ip-node1-high-1
    labels:
      diamanti.com/app: ip-node1-high-1
  spec:
    selector:
      matchLabels:
        diamanti.com/app: ip-node1-high-1
    template:
      metadata:
        labels:
          diamanti.com/app: ip-node1-high-1
      spec:
        containers:
        - env:
          - name: RT
            value: '60000'
          - name: RW
            value: randrw
          - name: RWRPCT
            value: '70'
          - name: QD
            value: '16'
          - name: BLOCK_SIZE
            value: 16k
          image: diamanti/fio-rw:0.1
          imagePullPolicy: IfNotPresent
          name: fio
          volumeMounts:
          - mountPath: "/data"
            name: vol-node1-high-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - name: vol-node1-high-1
          persistentVolumeClaim:
            claimName: vol-node1-high-1
kind: List
metadata: {}
